import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { fetchAPI, dataGlobal } from "@/lib/api";
import { generateSeo } from "@/lib/seo";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// export async function generateMetadata(): Promise<Metadata> {
//   const data = await fetchAPI(dataGlobal);

//   return generateSeo(data?.global?.defaultSeo);
// }
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const data = await fetchAPI(dataGlobal);

  const header = data?.global?.header;
  const footer = data?.global?.footer;

  //  console.log('footer', footer);

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header dataHeader={header} />
        {children}
        <Footer dataFooter={footer} />
      </body>
    </html>
  );
}
